name: osis_vote
description: "Aplikasi Pemilihan Ketua OSIS SMPN 13 Malang"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # State Management
  get: ^4.6.6

  # UI & Animation
  animate_do: ^2.1.0
  cupertino_icons: ^1.0.8

  # Fonts & SVG Support
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/icon/
